In [2]:
import torch
import torch.optim as optim
import numpy as np

In [3]:
# Random seed to make results deterministic and reproducible
torch.manual_seed(0)

In [7]:
sample = " if you want you"
set(sample) #set data에서는 순서는 의미가 없다.

{' ', 'a', 'f', 'i', 'n', 'o', 't', 'u', 'w', 'y'}

In [8]:
# make dictionary
char_set = list(set(sample))
print(char_set)
char_dic = {c: i for i, c in enumerate(char_set)}
print(char_dic)

['t', 'n', 'u', ' ', 'f', 'o', 'y', 'i', 'w', 'a']
{'t': 0, 'n': 1, 'u': 2, ' ': 3, 'f': 4, 'o': 5, 'y': 6, 'i': 7, 'w': 8, 'a': 9}


In [11]:
# hyper parameters
dic_size = len(char_dic)
hidden_size = len(char_dic)
learning_rate = 0.1

In [17]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(3, k=0, dtype=float)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(3, k=1, dtype=float)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [20]:
np.eye(3, k=-1, dtype=float)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [23]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
np.eye(10)[3]

array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

In [25]:
# data setting
sample_idx = [char_dic[c] for c in sample]
x_data = [sample_idx[:-1]]
x_one_hot = [np.eye(dic_size)[x] for x in x_data]
y_data = [sample_idx[1:]]

In [26]:
x_data

[[3, 7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5]]

In [27]:
x_one_hot

[array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])]

In [28]:
y_data

[[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]]

In [29]:
# transform as torch tensor variable
X = torch.FloatTensor(x_one_hot)
Y = torch.LongTensor(y_data)

C:\Users\jinou\AppData\Local\Temp/ipykernel_8652/1455435457.py:2: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  ..\torch\csrc\utils\tensor_new.cpp:201.)
  X = torch.FloatTensor(x_one_hot)


In [30]:
# declare RNN
rnn = torch.nn.RNN(dic_size, hidden_size, batch_first=True)

In [31]:
# loss & optimizer setting
criterion = torch.nn.CrossEntropyLoss()
optimizer = optim.Adam(rnn.parameters(), learning_rate)

In [32]:
# start training
for i in range(50):
    optimizer.zero_grad()
    outputs, _status = rnn(X)
    loss = criterion(outputs.view(-1, dic_size), Y.view(-1))
    loss.backward()
    optimizer.step()

    result = outputs.data.numpy().argmax(axis=2) #index가 2, 가장 큰 값을 가지는 인텍스를 가져온다?
    result_str = ''.join([char_set[c] for c in np.squeeze(result)])
    print(i, "loss: ", loss.item(), "prediction: ", result, "true Y: ", y_data, "prediction str: ", result_str)

0 loss:  2.390125036239624 prediction:  [[7 0 5 7 8 7 7 7 8 5 8 7 7 8 7]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  itoiwiiiwowiiwi
1 loss:  2.0528852939605713 prediction:  [[7 6 5 6 5 8 5 8 6 5 8 5 6 5 8]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  iyoyowowyowoyow
2 loss:  1.7891815900802612 prediction:  [[7 4 1 6 5 2 5 8 3 1 6 5 6 5 2]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  ifnyouow nyoyou
3 loss:  1.5983966588974 prediction:  [[7 4 1 6 5 2 4 8 3 1 0 5 6 5 2]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  ifnyoufw ntoyou
4 loss:  1.4671063423156738 prediction:  [[7 4 1 6 5 2 2 8 3 1 0 5 6 5 2]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  ifnyouuw ntoyou
5 loss:  1.3683114051818848 prediction:  [[7 4 3 6 5 2 3 8 9 1 0 5 6 5 2]] true Y:  [[7, 4, 3, 6, 5, 2, 3, 8, 9, 1, 0, 3, 6, 5, 2]] prediction str:  if you wantoyou
6 loss:  1.290